spring:
  application:
    name: media-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.136.101:8848
      config:
        namespace: 245fe186-8a54-4952-8aed-b2cac4c75c2e
        file-extension: yml
        refresh-enabled: true
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?refresh=true
