spring:
  application:
    name: search-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.136.101:8848
      config:
        namespace: 245fe186-8a54-4952-8aed-b2cac4c75c2e
        file-extension: yml
        refresh-enabled: true
  data:
    mongodb:
      host: 192.168.136.101
      port: 27017
      database: leadnews
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?refresh=true
      - nacos:common.yml
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://192.168.136.101:9200