spring:
  application:
    name: schedule-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.136.101:8848
      config:
        namespace: 245fe186-8a54-4952-8aed-b2cac4c75c2e
        file-extension: yml
        refresh-enabled: true
  rabbitmq:
    username: lei
    password: 123456
    virtual-host: /
    host: 192.168.136.101
    port: 5672
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?refresh=true
      - nacos:common.yml


